### ISSUE TITLE
Can't get it run

### ISSUE THREAD

**Issue by socbrian** [nickdelgrosso/hellolist#1]
install via pip in windows with 2.7.14. Got errors for not having  BeautifulSoup so I installed that via pip as well. I am getting the following error. Any help, might try and reinstall python with v3.x

```
Traceback (most recent call last):
  File "C:\Users\socbr\.platformio\python27\Scripts\hellolist-script.py", line 11, in <module>
    load_entry_point('hellolist==1.0', 'console_scripts', 'hellolist')()
  File "c:\users\socbr\.platformio\python27\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\socbr\.platformio\python27\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "c:\users\socbr\.platformio\python27\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
  File "c:\users\socbr\.platformio\python27\lib\site-packages\pkg_resources\__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\socbr\.platformio\python27\lib\site-packages\hellolist\__main__.py", line 3, in <module>
    import pandas as pd
ImportError: No module named pandas
```

**Comment by socbrian** [comment]
Installed 3.6.5 (windows 10)
easy-install BeautifulSoup4 
pip install pandas
pip install lxml

Got command prompt to open explorer so I am going to close this issue. Getting other issues, but will troubleshoot and open new issue.
